# Generated by Django 4.0.3 on 2022-04-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abc',
            name='c_calc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='abc',
            name='task',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='abc',
            name='a',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='abc',
            name='b',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='abc',
            name='c',
            field=models.IntegerField(),
        ),
    ]
