# Generated by Django 4.0.3 on 2022-04-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_abc_c_calc_abc_task_alter_abc_a_alter_abc_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='a',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abc',
            name='b',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abc',
            name='c',
            field=models.IntegerField(default=0),
        ),
    ]
