# Generated by Django 4.0.4 on 2022-04-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_abc_c_calc_alter_abc_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='task',
            field=models.CharField(default='Ровна ли С сумме A и B ?', max_length=256),
        ),
    ]
